- scripts/README.md
- scripts/incentive-spreadsheet-to-json.ts
- scripts/lib/spreadsheet-mappings.ts
- make state directory if it doesn't exist
- don't write the invalid records if there aren't any, and clear out previous versions if there are
- add an editorial notes column to the mapping, which we added to Colorado to document records that we don't intend to ever show (open to suggestions for a different name). This won't affect existing spreadsheets without this column.
> Add editorial notes column and better devex for writing outputs.

- src/schemas/v1/incentive.ts
- test/fixtures/v1-co-81657-state-utility-lowincome.json
The runtime validations aren't necessary since we validate that any launched items have the name and url by the schema in locales.ts. This change allows us to serve beta items without those attributes.
Not having the CO file in a previous PR was an omission.
> Remove name/url requirements for beta items and add CO test fixture.

- src/lib/incentive-relationship-calculation.ts
- src/lib/state-incentives-calculation.ts
- test/fixtures/test-incentives.json
- test/lib/incentive-relationships.test.ts
If an incentive was marked as ineligible before relationships were checked (e.g. due to income, owner status, etc), the relationships logic should not be allowed to mark it as eligible.
**Test plan**
Added a unit test for a case where an income-ineligible incentive would have been accidentally marked as eligible by the relationships logic previously.
> Add concept of permanently ineligible incentives

- data/AZ/incentives.json
- data/programs.json
- scripts/update-fixtures.sh
- src/data/programs.ts
- test/fixtures/v1-az-85702-state-utility-lowincome.json
- test/fixtures/v1-co-81657-state-utility-lowincome.json
- test/routes/v1.test.ts
Adds some incentives that were mislabeled by collector as "Other" that actually fit into one of our supported categories, and fix some redundant program names generated by the script.
> Add incentives missed by JSON script

- data/CT/incentives.json
- data/authorities.json
- data/low_income_thresholds.json
- data/programs.json
- src/data/programs.ts
- test/fixtures/v1-ct-06002-state-utility-lowincome.json
Also fixed the wording of some descriptions to better differentiate between the incentives, as suggested by testing feedback.
**Test Plan**
Updated the low income test fixture since they are now eligible for the new EV incentives as well.
> Adding EV incentives for CT based on testing feedback

- data/CO/incentives.json
- data/authorities.json
- src/data/authorities.ts
- src/lib/fetch-amis-for-address.ts
- src/lib/fetch-amis-for-zip.ts
- src/lib/incentives-calculation.ts
- src/lib/income-info.ts
- src/lib/state-incentives-calculation.ts
- src/lib/utilities-for-location.ts
- src/schemas/v1/location.ts
- test/data/schemas.test.ts
- test/fixtures/v1-02807-state-items.json
- test/fixtures/v1-02903-state-utility-lowincome.json
- test/fixtures/v1-15289-homeowner-80000-joint-4.json
- test/fixtures/v1-80212-homeowner-80000-joint-4.json
- test/fixtures/v1-az-85701-state-utility-lowincome.json
- test/fixtures/v1-az-85702-state-utility-lowincome.json
- test/fixtures/v1-co-81657-state-utility-lowincome.json
- test/fixtures/v1-ct-06002-state-utility-lowincome.json
- test/fixtures/v1-ny-11557-state-utility-lowincome.json
- test/fixtures/v1-va-22030-state-utility-lowincome.json
- test/fixtures/v1-vt-05401-state-utility-lowincome.json
- test/lib/incentive-relationships.test.ts
- test/lib/incentives-calculation.test.ts
City and County are different kinds of local authorities and the logic for matching them is different, so we split them here and add support for serving them in the API (previously they've been filtered out).
Summary of algorithm:
1. When looking up location information, use the zip code to return a county and city for the request, not just a state ID.
2. Require that for any incentive with a county/city authority type, that authority has county and possibly city attributes defined in authorities.json. This is enforced in tests.
3. For county incentives, the request county and authority county need to match. For city incentives, both the county *and* city attributes need to match, because there can be multiple cities with the same name in a state.
I can add documentation in a README about …
> Split local incentives into city and county types and add support for serving them.

- data/ira_incentives.json
- data/programs.json
- src/data/programs.ts
- test/fixtures/v0-80212-homeowner-80000-joint-4.json
- test/fixtures/v1-02807-state-items.json
- test/fixtures/v1-15289-homeowner-80000-joint-4.json
- test/fixtures/v1-80212-homeowner-80000-joint-4.json
- test/lib/i18n.test.ts
These acronyms are terrible but they're official, so...
https://app.asana.com/0/1204738794846444/1206378369410361
I changed the program identifiers in JSON, which wasn't strictly
necessary (they're never shown in the API) but I think is worthwhile.
`yarn test`. `grep -i` for "heehr" and "homes" to make sure nothing was missed.
> Update program names: HEEHR -> HEAR and HOMES -> HER

- scripts/lib/spreadsheet-mappings.ts
Splitting out of https://github.com/rewiringamerica/api.rewiringamerica.org/pull/277 to not muddy the waters there. Adding "Bonus Details" as bonus description column and "Questions".
> Add other supported column names from incentive-a-thon

- scripts/README.md
- scripts/incentive-spreadsheet-registry.ts
- scripts/lib/authority-and-program-updater.ts
- scripts/lib/spreadsheet-mappings.ts
- test/scripts/authority-and-program-updater.test.ts
Added two more supported columns from incentive-a-thon spreadsheet, and added alphabetization of authorities' file. Typical json sorting wasn't successful as the key's name was the value to sort by, which wouldn't parse when defining the sort function.
That being said, a generalized alphabetization solution for both programs and authorities is also being experimented with, but this simpler solution is viable due to incentive calculation being sorted by state locations of incentives.
Programs still need to be sorted, and README details this.
> Add supported columns, add alphabetization of authorities.

- data/AZ/incentives.json
- src/data/ira_incentives.ts
- src/data/state_incentives.ts
- src/data/types/amount.ts
- src/lib/incentives-calculation.ts
- test/fixtures/test-incentives.json
We didn't have `additionalProperties: false` on our incentive/amount schemas, which was letting unexpected fields creep in.
We *do* want to keep amount minimum, even though we're not using it on the frontend, as 4 different states have that field in their JSON already, so I've added it to the schema.
We want to get rid of item_type, which was deprecated and largely removed a while back.
> Add amount minimum, remove item_type, don't accept add'l properties.

- src/lib/incentives-calculation.ts
- src/schemas/v1/calculator-endpoint.ts
- test/fixtures/v1-02807-state-items.json
- test/fixtures/v1-02903-state-utility-lowincome.json
- test/fixtures/v1-15289-homeowner-80000-joint-4.json
- test/fixtures/v1-80212-homeowner-80000-joint-4.json
- test/fixtures/v1-az-85701-state-utility-lowincome.json
- test/fixtures/v1-az-85702-state-utility-lowincome.json
- test/fixtures/v1-co-81657-state-utility-lowincome.json
- test/fixtures/v1-ct-06002-state-utility-lowincome.json
- test/fixtures/v1-ny-11557-state-utility-lowincome.json
- test/fixtures/v1-va-22030-state-utility-lowincome.json
- test/fixtures/v1-vt-05401-state-utility-lowincome.json
These aren't being used in the frontend, and we've long known they're
a bit iffy in various ways. v0 is untouched.
Task to remove from API: https://app.asana.com/0/1204738794846444/1206540986137853
Old task to remove from frontend, where we discussed some of the problems:
https://app.asana.com/0/1205057814651000/1205608789805592/f
`yarn test`, look at fixture changes.
> Remove savings from API v1

- data/AZ/incentives.json
- data/CO/incentives.json
- data/CT/incentives.json
- data/NY/incentives.json
- data/RI/incentives.json
- data/VA/incentives.json
- data/VT/incentives.json
- src/data/state_incentives.ts
- src/lib/incentives-calculation.ts
- src/lib/state-incentives-calculation.ts
- src/routes/v0.ts
- src/schemas/v1/incentive.ts
- test/fixtures/test-incentives.json
- test/fixtures/v1-02807-state-items.json
- test/fixtures/v1-02903-state-utility-lowincome.json
- test/fixtures/v1-15289-homeowner-80000-joint-4.json
- test/fixtures/v1-80212-homeowner-80000-joint-4.json
- test/fixtures/v1-az-85701-state-utility-lowincome.json
- test/fixtures/v1-az-85702-state-utility-lowincome.json
- test/fixtures/v1-co-81657-state-utility-lowincome.json
- test/fixtures/v1-ct-06002-state-utility-lowincome.json
- test/fixtures/v1-ny-11557-state-utility-lowincome.json
- test/fixtures/v1-va-22030-state-utility-lowincome.json
- test/fixtures/v1-vt-05401-state-utility-lowincome.json
- test/lib/incentives-calculation.test.ts
Switching from `.type` to `.payment_methods[0]` in various backend calls is necessary since our CalculatedIncentive type no longer reliably has a `type` property. We could split up that type but I figured it was just easier to start using `payment_methods[0]` in the calculations anyway.
To make that safer, I added minItems requirements to the JSON schema def for payment_methods and owner_status; now those arrays can't be empty.
Tested: submitted an empty payment_methods array in one of the incentives and confirmed we got a test failure.
> Remove type from v1 schema.

- scripts/generate-misc-state-data.ts
- scripts/incentive-spreadsheet-to-json.ts
- scripts/lib/spreadsheet-standardizer.ts
- test/scripts/incentive-spreadsheet-to-json.test.ts
- test/scripts/spreadsheet-standardizer.test.ts
We have a clearer separation of concerns in the spreadsheet to json flow (and it will get clearer in subsequent CLs). That flow does:
1. Standardizes column and value names (and formats)
2. Converts formats from csv to json (coming soon)
3. Does some additional processing/derivation to take a collected/raw record to the version we actually save
I'm doing some method and variable renaming now to reflect this and to declutter some upcoming changes.
> Rename spreadsheet standardizer methods.

- scripts/lib/format-converter.ts
- src/data/state_incentives.ts
- test/scripts/format-converter.test.ts
- test/scripts/spreadsheet-standardizer.test.ts
This is not integrated yet – that is an upcoming PR.
I was tempted to call these methods csvToJson, but really csv-parse has already converted csv to json; it's just a flat object that we can't do interesting things with. These methods "inflate" that object and optionally validate it.
I noticed an error or two in the previous schema as testing, so those are fixed here.
> Add format-converter to bridge from csv-parse to our collected schema.

- package.json
Our test suite's grown a lot, and it would be nice to have an easy way to only run some tests while working on individual files. `yarn testfilter <path>` does this.
In yarn 2, there's a slicker way to do this that doesn't require a separate command, but I couldn't figure out an easy way to do this in yarn 1.
> Add testfilter yarn script for running a subset of tests.

- scripts/incentive-spreadsheet-to-json.ts
- scripts/lib/spreadsheet-standardizer.ts
- src/data/state_incentives.ts
- test/scripts/incentive-spreadsheet-to-json.test.ts
This incorporates the format-converter and collected schema into the spreadsheet-to-json flow. Now we first validate that the collected data is valid under our spreadsheet schema, then take the collected data and turn it into a refined StateIncentive. This may surface some more nits in the short-term while we clean up the spreadsheets, but in the long-term is better since we can keep those spreadsheets healthy from the get-go.
It simplifies the `refineCollectedData` method since we can assumed we're working with valid collected data from the beginning. However, it did require rewriting a bit of the LowIncomeThreshold part since we could no longer just assign a string.
After this PR, I'll also pull out a stand-alone version of the CollectedFields validation that can be run on our …
> Validate spreadsheets first in spreadsheet-to-json flow.

- data/VT/incentive_relationships.json
- data/VT/incentives.json
- data/programs.json
- test/fixtures/v1-vt-05401-state-utility-lowincome.json
Some incentives are brought through a partnership of a state entity with a utility company. We are removing a couple of incentives here that are redundant.
> Fix Vermont Incentives so we don't double up on the same incentive.

- scripts/README.md
- scripts/generate-utility-data.ts
I realized I was going through a somewhat finicky process to clean up
the utility data for each state, and this is now has to be an integral
part of the spreadsheet-to-JSON process, so I'd better document it.
I'm not yet totally sure where this process should fit into the
overall process for each state, so interested in feedback on that.
Also I realized I have no plan for running this script on a regular
basis. I have no idea how often ENERGY STAR updates the data, so I
thought the script should at least print out the last-updated date (in
the first cell of the spreadsheet) so we can start to figure that out.
Read it. Run the script.
> Document generate-utility-data script in README

- scripts/incentive-spreadsheet-to-json.ts
- test/data/spreadsheets-health.test.ts
We get better reuse of the spreadsheet-to-json process if decoupled from the file reading/writing parts. So this just moves the data processing into a single method and then file reading/writing happens separately. As part of that, we don't error out early when we find CollectedIncentive errors; we continue to try to validate StateIncentives and surface both separately to the user if they exist.
I also realized the updateJsonFiles method handles file-clearing already so a bit of tidying up there too.
> Refactor spreadsheet-to-json to avoid writing files.

- scripts/lib/authority-and-program-updater.ts
- test/scripts/authority-and-program-updater.test.ts
This is part of making the generate-misc-state-data script fully automated and repeatable.
This is mostly moving code. The actual changes are:
1. We no longer error when overwriting an existing state. That's intentional so the script can be run repeatedly.
2. Moving the updating process into a separate method for easier testing and adding some tests.
> Make authority updater overwrite existing states and add more testing.

- scripts/incentive-spreadsheet-to-json.ts
- scripts/lib/format-converter.ts
- scripts/lib/spreadsheet-mappings.ts
- src/data/state_incentives.ts
- test/scripts/format-converter.test.ts
- test/scripts/incentive-spreadsheet-to-json.test.ts
I figured we'd need this eventually, but it seems like now is the time since:
1. PEP folks requested this so that when there are records in the spreadsheet that shouldn't appear in the JSON, they don't have to keep deleting the generated output from the spreadsheet-to-json flow.
2. Upcoming test/script will verify equivalence of spreadsheet and JSON data, so we do need a way to mark that some records can be skipped.
Design choices:
- it's omit_from_api rather than serve_in_api because serving should be the default
- we drop these records entirely now, though as a follow-up, I'll probably have them returned as a separate category so they can be properly accounted for.
> Add omit_to_api to our schema to filter out unwanted records.

- scripts/README.md
- scripts/incentive-spreadsheet-registry.ts
- scripts/update-descriptions.ts
After https://github.com/rewiringamerica/api.rewiringamerica.org/pull/319, these fields are basically not used, and we should be configuring any renaming in one place (spreadsheet-mappings).
I suspect this script is not long for this world anyway, since spreadsheet-to-json is a more comprehensive way to update spreadsheet files, but we can keep it for now in case someone wants to only run the Spanish translation updates.
> Stop specifying individual fields in spreadsheet registry.

- data/CO/incentives.json
- data/authorities.json
- data/geo_groups.json
- scripts/lib/spreadsheet-mappings.ts
- scripts/update-fixtures.sh
- src/data/authorities.ts
- src/data/geo_groups.ts
- src/data/state_incentives.ts
- src/lib/incentives-calculation.ts
- src/lib/state-incentives-calculation.ts
- test/data/geo_groups.test.ts
- test/data/schemas.test.ts
- test/data/utilities.test.ts
- test/fixtures/v1-80517-estes-park.json
- test/fixtures/v1-80517-xcel.json
- test/fixtures/v1-dc-20303-state-city-lowincome.json
- test/routes/v1.test.ts
This is where I got to following the comments on #322.
- There's a new concept that I'm calling "geo groups" (open to
bikeshedding). Each one can contain a set of cities, a set of
counties, and a set of utilities (in the form of their IDs from
authorities.json).
Geo groups are defined in a new file, `data/geo_groups.json`. I
considered defining them in authorities.json, but I think it's
better to clearly separate the concept of authority from geographic
eligibility; that was part of the whole point of this, and I kind of
lost sight of it before. A geo group is not an authority (although
in practice there's probably very significant overlap); it's just a
set of utilities/cities/counties.
One potentially confusing thing is that geo group IDs are a totally
separate namespace from all the …
> [RFC] Add concept of "geo groups"

- src/routes/v1.ts
- src/schemas/v1/calculator-endpoint.ts
- src/schemas/v1/location.ts
- src/schemas/v1/utilities-endpoint.ts
- test/routes/v1.test.ts
The `location` param being a key-value map makes it a little awkward
for some HTTP tooling. See https://rewiringameri-g3x1100.slack.com/archives/C04E4THEGMT/p1707244817589029
Instead, put the `zip` and `address` params at the top level. This PR
adds them and keeps `location` as-is, until we can switch over the
frontend, at which time we'll remove `location`. One of the three
params is required.
`yarn test`. Tested the `address` param manually with:
`curl 'http://localhost:3000/api/v1/calculator?owner_status=homeowner&household_income=50000&tax_filing=single&household_size=1&address=82%20Smith%20St,Providence'`
and made sure RI-specific incentives show up.
> Add "zip" and "address" top-level params

- src/app.ts
This started when I upgraded fastify-cli. Switch to the new API that
the error message says.
`yarn test` no longer shows the error. Run `yarn dev` and watch the
logs as you make a curl request; make sure the "request completed"
message includes a sensible responseTime (in milliseconds).
> Fix Fastify deprecation warning

- package.json
- yarn.lock
They accepted my PR! This bumps some dependency versions that we had
dependabot alerts for.
`curl 'http://localhost:3000/api/v1/calculator?owner_status=homeowner&household_income=50000&tax_filing=single&household_size=1&location\[address\]=82%20Smith%20St,Providence'`
(The `location[address]` part makes the server use Geocodio)
> Upgrade geocodio-library-node

- data/data_partners.json
- src/data/data_partners.ts
- src/lib/incentives-calculation.ts
- src/lib/state-incentives-calculation.ts
- src/schemas/v1/calculator-endpoint.ts
- test/fixtures/il-60304-state-utility-lowincome.json
- test/fixtures/v1-02807-state-items.json
- test/fixtures/v1-02903-state-utility-lowincome.json
- test/fixtures/v1-15289-homeowner-80000-joint-4.json
- test/fixtures/v1-80212-homeowner-80000-joint-4.json
- test/fixtures/v1-80517-estes-park.json
- test/fixtures/v1-80517-xcel.json
- test/fixtures/v1-az-85701-state-utility-lowincome.json
- test/fixtures/v1-az-85702-state-utility-lowincome.json
- test/fixtures/v1-co-81657-state-utility-lowincome.json
- test/fixtures/v1-ct-06002-state-utility-lowincome.json
- test/fixtures/v1-dc-20303-state-city-lowincome.json
- test/fixtures/v1-ga-30033-utility.json
- test/fixtures/v1-mi-48103-state-utility-lowincome.json
- test/fixtures/v1-nv-89108-state-utility-lowincome.json
- test/fixtures/v1-ny-11557-state-utility-lowincome.json
- test/fixtures/v1-va-22030-state-utility-lowincome.json
- test/fixtures/v1-vt-05401-state-utility-lowincome.json
- test/fixtures/v1-wi-53703-state-utility-lowincome.json
1. Adds support for a new concept, data partners (see comment in src/data/data_partners.ts for description). Basically there are some orgs, like NCEF in Nevada, who help us with data collection and reviewing incentives, so we want to feature their logo in the calculator. However, they don't fit neatly into any existing data structures -- they're not really authorities since they don't offer incentives directly. This PR adds a concept of "data partners" to represent these organizations
2. Creates the first data partner, NCEF in NV
3. Adds `data_partners` to the API V1 response
4. Updates fixtures. Should be `data_partners: {}` for all states except NV
We need to be able to feature NCEF's logo in the calculator. See context here https://rewiringameri-g3x1100.slack.com/archives/C04E4THEGMT/p1 …
> Support for data partners with logos

- data/geo_groups.json
- scripts/generate-misc-state-data.ts
- scripts/lib/authority-and-program-updater.ts
- scripts/lib/data-refiner.ts
- scripts/lib/spreadsheet-mappings.ts
- src/data/geo_groups.ts
- src/data/state_incentives.ts
- test/scripts/authority-and-program-updater.test.ts
- Updates generate-misc-state-data to create entries in
geo_groups.json for any authorities of type "other", with empty
lists to be filled in by the engineer.
A couple of wrinkles: the standardizer that gets created in this
script has empty value mappings, which means the check for authority
type has to look for the spreadsheet string `Other` rather than the
standardized `other`. I don't know why the value mappings are empty
in this case, but looking for the unstandardized value feels wrong.
The standardizer is also created in strict mode, which means it
errors out because there are extra columns in the CO and VT
spreadsheets now ("description character count"/"description word
count" and "questions / comments" respectively). I had to turn off
strict mode to test the changes.
- Updates …
> Update scripts to handle geo_groups

- data/low_income_thresholds.json
- scripts/lib/data-refiner.ts
- src/data/low_income_thresholds.ts
- src/lib/state-incentives-calculation.ts
- test/data/low_income_thresholds.test.ts
- test/scripts/incentive-spreadsheet-to-json.test.ts
This isn't fully complete, but I wanted to get initial feedback before writing tests.
After doing some investigation, I didn't want to go the geo_groups route for low_income configuration for a couple reasons:
1. low-income thresholds are of interest to external stakeholders, and I think it will complicate things for all parties if at some point in the spreadsheet-to-json process, we're replacing data that is standalone and human-readable with an enum key that only makes sense if referencing a separate dataset (this reasoning applies to geo groups too but is maybe less important there)
2. in the spreadsheets, data collectors tend to put notes in the income column that aren't shared across all records that have the same low-income thresholds. Some of these refer to the non-low-income …
> Switch to configuring low-income explicitly by record.

- data/geo_groups.json
- scripts/lib/authority-and-program-updater.ts
- scripts/lib/data-refiner.ts
- src/data/geo_groups.ts
- test/data/geo_groups.test.ts
- test/data/schemas.test.ts
- test/scripts/authority-and-program-updater.test.ts
- test/scripts/data-refiner.test.ts
The implementation in refineCollectedData is a little repetitive, but I didn't see an obvious way to refactor it.
> Update geo groups to be configured similar to low-income thresholds.

- data/data_partners.json
- test/fixtures/v1-dc-20303-state-city-lowincome.json
Adds Electrify DC's logo to the list of data partners for DC
> Add Electrify DC logo to data partners

- src/data/types/states.ts
- test/data/schemas.test.ts
Moves VA and DC to the list of launched states
Next step: after launch, remove "beta" state status in tests/fixtures, follow up on Spanish translations
> Launch VA and DC to launched states

- scripts/update-fixtures.sh
- src/routes/v1.ts
- src/schemas/v1/calculator-endpoint.ts
- src/schemas/v1/location.ts
- src/schemas/v1/utilities-endpoint.ts
- test/routes/v1.test.ts
- yarn.lock
This is the final step of migrating to separate top-level `zip` and
`address` parameters: removing the old nested parameter.
The embed frontend is already switched over, and there should be no
other clients of v1, so although this is a breaking change it should
be safe.
`yarn lint`, `yarn test`. Run the update-fixtures script and make sure
the updates all succeed and there are no changes.
> Remove location parameter from v1

- scripts/README.md
- scripts/generate-utility-data.ts
There's a filesystem error upon reading the authorities.json file
towards the end of the script. (I don't know why I didn't see this
during testing?) Switching to the synchronous fs APIs seems to fix it,
so just do that rather than sink more time into investigating. None of
these reads/writes would happen concurrently anyway, so there's no
real downside to this.
Run the script and don't get an `EBADF` error.
> Don't use the fs/promises API in generate-utility-data

- .gitignore
- package.json
- scripts/README.md
- scripts/incentive-spreadsheet-registry.ts
- scripts/incentive-spreadsheet-to-json.ts
- scripts/lib/auth-helper.ts
- scripts/lib/format-converter.ts
- test/scripts/format-converter.test.ts
- test/scripts/incentive-spreadsheet-to-json.test.ts
- yarn.lock
This is half of the Google Sheets <-> JSON conversion. The other half is coming shortly.
Welcoming @mmezher's thoughts but @oyamauchi, I think it's best if you're the primary reviewer. Since you'll be absorbing any spreadsheet-json work, I want to make sure you're on board.
As mentioned in [this thread](https://rewiringameri-g3x1100.slack.com/archives/C04E4THEGMT/p1710441552470399), hyperlinks are a problem for the conversion since they are not easily stored in JSON. This is especially true because you can have multiple links in the same cell, and it becomes difficult to store this without making it very difficult for humans to edit the JSON. So as decided in that thread, we're condensing the hyperlinks to text.
To actually deploy this new method, I've changed the spreadsheet-to-json flow …
> Add way to read Google Sheets API and save hyperlinks into JSON.

- data/authorities.json
- scripts/data/zip-to-utility.csv
- scripts/generate-utility-data.ts
Addresses, the following. 
In https://github.com/rewiringamerica/api.rewiringamerica.org/pull/368, new logic was added to generate all the utilities in authorities.json from the utility CSVs we have. This added a bunch of utilities to existing states, but these weren't audited. This ticket is to go through the utilities for IL in authorities.json and figure out:
Are any of them gas only?
Are any of them referencing the same utility (ex: in PA I had PECO and PECO Electric Corp which were referencing the same utility)
Do any of them have different customer-facing names?
How to fix these issues is documented here: https://github.com/rewiringamerica/api.rewiringamerica.org/blob/main/scripts/README.md#utility-data
Ticket: https://app.asana.com/0/1206629812394927/1206892313217560/f
> Update IL Utility names to use common names after audit. 

- data/PA/incentives.json
- src/data/programs/pa_programs.ts
- test/fixtures/v1-pa-17555-state-lowincome.json
Fixing QA issues that came up during the testing party today, as well as some feedback we got from our contacts at Duquesne who have been reviewing the incentives spreadsheet. 
Main changes:
- Add 2 additional EV incentives. Duquesne emailed and wanted these included. Technically 1 incentive but we need to list twice, once for new and once for used EV
- Originally I had all PA incentives listed as applies to both homeowner and renter because none of the programs specified homeowner only, so I assumed both were eligible. However Hannah brought up [this mapping](https://github.com/rewiringamerica/incentive-data-llm/blob/main/src/constants.ts#L16) that we can use, so in this PR I've updated to be consistent with that mapping
- Added ® to all references to Energy Star
- Updated a couple …
> Address PA QA findings and Duquesne feedback

- src/data/programs.ts
- src/routes/v1.ts
- src/schemas/v1/incentive.ts
- test/fixtures/v1-02807-state-items.json
- test/fixtures/v1-15289-homeowner-80000-joint-4.json
- test/fixtures/v1-80212-homeowner-80000-joint-4.json
Putting links to our info about the IRA programs in `item.url` doesn't
make conceptual sense. This adds an optional `more_info_url` field at
the top level of incentives, and makes `program_url` required.
To make `program_url` required, I had to add program URLs to the IRA
programs in the data. There are official IRS pages for all the tax
credits, so I used those. The rebate programs don't have official
pages, so I just reused the URLs we're using as the more-info URLs on
those incentives.
https://app.asana.com/0/1206661332626418/1206843501113812
`yarn test`
> Add more_info_url to the v1 API; make program_url required

- data/AZ/authorities.json
- data/CO/authorities.json
- data/CT/authorities.json
- data/DC/authorities.json
- data/GA/authorities.json
- data/IL/authorities.json
- data/MI/authorities.json
- data/NV/authorities.json
- data/NY/authorities.json
- data/OR/authorities.json
- data/PA/authorities.json
- data/RI/authorities.json
- data/VA/authorities.json
- data/VT/authorities.json
- data/WI/authorities.json
- scripts/README.md
- scripts/generate-utility-data.ts
- scripts/lib/authority-and-program-updater.ts
- src/data/authorities.ts
- test/scripts/authority-and-program-updater.test.ts
We're about to populate authorities for every state's utilities in one
go, and that would make authorities.json unmanageably large. Since its
top-level key is already states, that makes it easy to split into one
file per state.
There's basically no downstream effect in the API server;
`authorities.ts` just recreates the same map that was previously in
the unified authorities.json. The scripts side is actually simplified
a bit.
The `state` key in a state's authorities is now optional, because we'll
be generating files with only a `utility` key.
https://app.asana.com/0/1206661332626418/1206882125337116
`yarn lint` and `yarn test`.
Followed the new-state process (running generate-utility-data and then
authority-and-program-updater) for CA to make sure it goes smoothly.
> Split authorities.json into a file for each state

- scripts/export-to-google-sheets.ts
- scripts/lib/format-converter.ts
- scripts/lib/spreadsheet-standardizer.ts
- test/scripts/format-converter.test.ts
- test/scripts/incentive-spreadsheet-to-json.test.ts
This is the other half of Google Sheet <-> JSON conversion; a continuation of https://github.com/rewiringamerica/api.rewiringamerica.org/pull/373. They're largely independent, though they both rely on the authentication helper and the changes to the spreadsheet-registry.
This is the CollectedIncentives -> Google Sheet direction. It uses the Google Sheets API to create a new spreadsheet. Right now, we only have the incentives data itself, but as a follow-up, I'll create other worksheets like the data model and the standardized enum values so that it is more comparable to our existing sheets (plus add data validation).
Notable assumption: the first alias in the FIELD_MAPPINGS and VALUE_MAPPINGS in spreadsheet-mappings.ts is considered the canonical human-readable spreadsheet version. I …
> Add method to export collected incentives to a Google sheet.

- scripts/lib/authority-and-program-updater.ts
I noticed recently that test time had ballooned – I was getting like 45 seconds to run all the tests. Did some debugging and the culprit was initializing the TS project at the top-level of this file instead of moving it into a function and doing as needed. Now we're back down to 23 seconds.
> Move project initialization into a function and cut test time in half.

- scripts/export-to-google-sheets.ts
Links in Google Sheets don't autoformat (e.g. become clickable) when written via API unless the formatting data is explicitly supplied. This is harder for us to do up-front (though is a valid alternative if we don't like this approach).
Instead, once we've written the sheet, we can simply use the API to read cell values and write them back as if the user had entered them. This triggers Google Sheets to format the input. Unfortunately I don't believe this is possible to do as part of initial spreadsheet creation.
For an alternative, we'd need a reliable URL detector regex and we'd have to scan through all the cells, finding links and then adding format data to each cell indicating where the link should be placed. That seemed harder overall since URL detection is probably a rabbit hole.
I …
> Add link formatting to Google Sheet exports.

- scripts/lib/spreadsheet-mappings.ts
This is a refactor prior to using it for more export-to-google work, but it's worth doing in its own right.
We don't have any type-safety for the values, but that's no different than before.
As part of doing this, I added values for filing_status since those were missing, plus the value descriptions.
Testing: prior to deleting the old version of VALUE_MAPPINGS, I logged both versions to the console and they had zero diffs.
> Refactor value mappings into field metadata.

- scripts/export-to-google-sheets.ts
- scripts/lib/format-converter.ts
- scripts/lib/google-sheets/incentives-sheet-exporter.ts
- test/scripts/format-converter.test.ts
- test/scripts/google-sheets/incentives-sheet-exporter.test.ts
Two related but separate changes:
1. introduce an argument to drop columns when reading them in in the flatToNested method.
2. introduce an argument to add the formula columns when writing them. They're hard-coded to the word/char count formulas, but the approach should work for other formulas if we need to add them in the future. It works because Google Sheets API has a valueRenderOption param that recognizes formulas when reading spreadsheet data.
The API is a bit awkward because it's not clear from the name `descriptionColumnName` that it would control formulas. If you prefer, we can introduce an additional boolean param called `addDescriptionFormulaColumns`, and if it's true, we require the column name as well.
Testing: unit tests, and ran on Colorado to make sure that we were …
> Add formula-based description word/char count columns.

- scripts/export-to-google-sheets.ts
- scripts/lib/google-sheets/incentives-sheet-exporter.ts
- scripts/lib/google-sheets/standardized-enums.ts
- test/scripts/google-sheets/incentives-sheet-exporter.test.ts
- test/scripts/google-sheets/standardized-enums.test.ts
[Sample output](https://docs.google.com/spreadsheets/d/1lS5htTOE2Nji9Nqy_6HzA50dZuPEYukb_G1tUXe63ys/edit#gid=0)
Notable diff from current approach: I currently have it so that users can edit the protected sheet; it just shows a warning. In my experience, the sheet protection has been more trouble than it's worth - see Slack for lots of examples of people needing sheets unlocked. I think we want the validations to discourage changes but ultimately allow people to make changes if they think the schema needs to be updated.
It's an easy change to switch to actual protection if you prefer, in which case I would make engineering-team@rewiringamerica.org editors.
Not in this PR
- there are other protected ranges in our templates like the example data row or the IDs column, but I think they are …
> Add data validations and sheet protection.

- src/routes/v1.ts
- src/schemas/v1/incentive.ts
- test/fixtures/il-60304-state-utility-lowincome.json
- test/fixtures/v1-02807-state-items.json
- test/fixtures/v1-02903-state-utility-lowincome.json
- test/fixtures/v1-15289-homeowner-80000-joint-4.json
- test/fixtures/v1-80212-homeowner-80000-joint-4.json
- test/fixtures/v1-80517-estes-park.json
- test/fixtures/v1-az-85701-state-utility-lowincome.json
- test/fixtures/v1-az-85702-state-utility-lowincome.json
- test/fixtures/v1-co-81657-state-utility-lowincome.json
- test/fixtures/v1-ct-06002-state-utility-lowincome.json
- test/fixtures/v1-dc-20303-state-city-lowincome.json
- test/fixtures/v1-ga-30033-utility.json
- test/fixtures/v1-mi-48103-state-utility-lowincome.json
- test/fixtures/v1-nv-89108-state-utility-lowincome.json
- test/fixtures/v1-ny-11557-state-utility-lowincome.json
- test/fixtures/v1-or-97001-state-lowincome.json
- test/fixtures/v1-pa-17555-state-lowincome.json
- test/fixtures/v1-va-22030-state-utility-lowincome.json
- test/fixtures/v1-vt-05401-state-utility-lowincome.json
- test/fixtures/v1-wi-53703-state-utility-lowincome.json
This is no longer used by the frontend, and the URLs now get
redirected to incentive-centered pages; I think the whole concept of a
URL for an item is dead.
v0 still uses the URLs, in the `more_info_url` field, so we can't
delete them. We can't even change them to the incentive-centric
`homes.rewiring` URLs, because these URLs are relative, and the host
is assumed to be `www`. So we'll be stuck with this until v0 can be deleted.
`yarn test`. Make sure the embed frontend does not use this field.
> Remove item.url from v1

- data/CO/authorities.json
- data/CO/incentive_relationships.json
- data/CO/incentives.json
- data/low_income_thresholds.json
- scripts/lib/authority-and-program-updater.ts
- src/data/programs/co_programs.ts
- test/fixtures/v1-80517-xcel.json
- test/fixtures/v1-co-81657-state-utility-lowincome.json
There are a bunch of diffs here that are unrelated to the refresh because the spreadsheet and JSON got out of sync :)
Refresh Diffs:
1. Two incentives added at the end – CO-543 and CO-544
2. Some incentives changed in the middle because their heat pump terms changed from 2023 to 2024.
3. Introduced two new low-income incentives which are bonuses
4. Updates of related files (authorities, programs, and test fixtures)
Unrelated diffs:
1. Fixing some typo spaces at the end of sentences
2. Fixing some cases where the text said "see link", which were being lost anyway (these were actual links and not just a reference to the utility's website). I don't think any of them were necessary.
3. Intentional loss of an incentive that we deemed had too little information to bother showing. Before we had …
> Small refresh of CO data based on Zero Homes feedback.

- data/data_partners.json
- test/fixtures/v1-dc-20303-state-city-lowincome.json
Linking images to confirm they are uploaded correctly:
https://storage.googleapis.com/rewiring-america-incentives-assets/dc-mayor.png
https://storage.googleapis.com/rewiring-america-incentives-assets/dc-doee.png
https://storage.googleapis.com/rewiring-america-incentives-assets/dc-seu.png
I resized to 100 height, which is consistent with the authority logos but smaller than the other partner logos. Feedback/correction welcome!
> add additional DC partner credits

- scripts/update-fixtures.sh
- src/data/types/states.ts
- test/fixtures/v1-15289-homeowner-80000-joint-4.json
- test/routes/v1.test.ts
Launch 🎉 Moving forward this because:
- We're doing an event in PA on 4/22 and this needs to be ready by then
- PA utilities have started working on integrating the embed into their sites, and to avoid using the `beta_states` flag these need to be live
> Release PA incentives

- src/lib/utilities-for-location.ts
- src/routes/v1.ts
- test/data/utilities.test.ts
- test/routes/v1.test.ts
We want to show real utility options to all users, not just in
launched/beta states. We now have the data, so we can remove the check.
https://app.asana.com/0/1206661332626418/1206843501113809
`yarn test` and updated tests/fixtures. Run queries for some states
that we haven't touched yet.
> Let /v1/utilities serve utilities for all states

- data/PA/incentives.json
We got some last minute feedback from Duquesne that they'd like to combine these 5 weatherization incentives ($400 each) into 1 incentive (Up to $2,000) before the public launch on Monday. They confirmed these rebates can be stacked and that they prefer this representation.
Open to ideas on the wording here for the description - this seems okay to me but the wording is a little weird to make sure it's under the 150 character limit.
Unfortunately this means we'll need to get the Spanish translation redone - I'll make a ticket for that but it may not be done by Monday, which I think is fine
> Combine Duquesne weatherization updates

- src/data/programs/co_programs.ts
Denver CASR requests we use a different link urgently. Assuming tests pass I will merge this ASAP.
> We are confirmed that the new RA tool will go out in our newsletter at the end of the week and are hoping that the Mayor will include in an Earth Day update as well.
> 
> Is there any way your team could update our link for each measure by the end of the week to: https://www.denvergov.org/Government/Agencies-Departments-Offices/Agencies-Departments-Offices-Directory/Climate-Action-Sustainability-Resiliency/Cutting-Denvers-Carbon-Pollution/High-Performance-Buildings-and-Homes/Electrify-Your-Home
> OR
> [www.denvergov.org/heatpumprebates](http://www.denvergov.org/heatpumprebates)
>  
> Want to make sure we are sending people to the most up-to-date locations and maximizing the announcements!
> fix Denver program link per CASR request

- data/CO/incentives.json
- src/data/programs/co_programs.ts
- test/fixtures/v1-co-81657-state-utility-lowincome.json
This is all from updating the spreadsheet. The City of Boulder
incentives are now just flat amounts, not percents. A Boulder County
solar incentive and state-level tax credit for batteries are removed.
I updated the Spanish descriptions myself; the updates are straightforward
and there are plenty of other examples to model them on.
https://app.asana.com/0/1206661332626418/1207127626720501/f
`yarn test`
> Colorado updates from EnergySmart

- data/CO/incentives.json
- test/fixtures/v1-co-81657-state-utility-lowincome.json
Fixes Walking Mountain incentive typos `qualitying` -> `qualifying`.
> Addresses a typo in CO incentive data as reported from a partner. 

- scripts/update-fixtures.sh
- src/routes/v1.ts
- src/schemas/v1/incentive.ts
- test/fixtures/il-60304-state-utility-lowincome.json
- test/fixtures/v1-02807-state-items.json
- test/fixtures/v1-02903-state-utility-lowincome.json
- test/fixtures/v1-15289-homeowner-85000-joint-4.json
- test/fixtures/v1-80517-estes-park.json
- test/fixtures/v1-80517-xcel.json
- test/fixtures/v1-84106-homeowner-80000-joint-4.json
- test/fixtures/v1-az-85701-state-utility-lowincome.json
- test/fixtures/v1-az-85702-state-utility-lowincome.json
- test/fixtures/v1-co-81657-state-utility-lowincome.json
- test/fixtures/v1-ct-06002-state-utility-lowincome.json
- test/fixtures/v1-dc-20303-state-city-lowincome.json
- test/fixtures/v1-ga-30033-utility.json
- test/fixtures/v1-il-60202-city-lowincome.json
- test/fixtures/v1-mi-48103-state-utility-lowincome.json
- test/fixtures/v1-mi-48825-city-lowincome.json
- test/fixtures/v1-nv-89108-state-utility-lowincome.json
- test/fixtures/v1-ny-11557-state-utility-lowincome.json
- test/fixtures/v1-or-97001-state-lowincome.json
- test/fixtures/v1-pa-17555-state-lowincome.json
- test/fixtures/v1-va-22030-state-utility-lowincome.json
- test/fixtures/v1-vt-05401-state-utility-lowincome.json
- test/fixtures/v1-vt-05845-vec-ev-low-income.json
- test/fixtures/v1-wi-53703-state-utility-lowincome.json
This is the beginning of the process of adding more granular item
types for heat pumps and weatherization. Individual incentives will
now pertain to multiple `Item`s.
The process will be:
1. Land and deploy this
2. Land and deploy rewiringamerica/embed.rewiringamerica.org#156
3. Land and deploy a PEP PR which is yet to come, similar to the embed one above (read from new field if available; fall back to existing one if not)
4. Update the backend to stop including the old single-valued field in responses.
5. Remove the support for the old field from the embed and PEP code
6. Start updating the underlying data, this getting rid of the "synthesize `items`" bit from this PR.
I decided to ditch the human-friendly `name`. It was a holdover from
v0, in which it was used to populate the table UIs …
> Add multi-valued "items" field

- data/CO/incentives.json
- test/fixtures/v1-80517-estes-park.json
- test/fixtures/v1-80517-xcel.json
- test/fixtures/v1-co-81657-state-utility-lowincome.json
Update CO EO incentive - remove erroneous space
I recently merged in https://github.com/rewiringamerica/api.rewiringamerica.org/pull/452, which contained an extra space. This fixes the issue.
> Update CO EO incentive - remove erroneous space

- src/data/ira_incentives.ts
- src/data/locale.ts
- src/data/types/items.ts
- src/lib/i18n.ts
This does not actually change any of the incentive data; just adds new
granular items to the schema.
I think this will be the best place to discuss the editorial matter of
exactly which items to add. Some of the decisions I made:
- I added `other_heat_pump` as a catchall for heat pump-like devices
that don't fall under `ducted_heat_pump`, `ductless_heat_pump`,
`central_air_conditioner`, `air_to_water_heat_pump`, or
`geothermal_heating_installation`. I don't know if such a thing
really exists, or if it does whether we care to include it in the API?
- Note that my plan is to deprecate
`heat_pump_air_conditioner_heater`, rather than use it as the catchall.
- I also added (a) `other_insulation` and (b) `other_weatherization`.
Respectively, these are for (a) insulation that isn't covered by …
> Add more items to the schema

- data/DC/incentives.json
- data/OR/incentives.json
- src/data/programs/or_programs.ts
- test/fixtures/v1-dc-20303-state-city-lowincome.json
- test/fixtures/v1-or-97001-state-lowincome.json
The DC incentives just got reordered for some reason (I diffed old and
new after sorting, and they're identical).
There were some actual changes to the OR incentives; they look
sensible, though I haven't verified them with the primary sources.
Since OR launch is still a ways off, I'll leave that for a full data
refresh later. I also had to update the spreadsheet a bit to fix missing
values in required fields.
`yarn test`
> Get check-spreadsheet-health passing again

- data/ira_incentives.json
We didn't update these upon launching the new consumer site content
because it wasn't in Spanish yet. Now it is.
Note that this affects v1 / the new calculator only. v0 and the old
embed still have to link to the `www` equipment pages (URLs in
`locales/{en,es}.json`) because those URLs are relative.
`yarn test`. Visit each URL to make sure it works.
> Update Spanish URLs for IRA incentives

- Dockerfile
- README.md
- package.json
- src/plugins/cors.ts
- yarn.lock
I keep having to apply this locally when testing the embed frontend
against local API changes, I figure it'll probably be generally
useful.
The plugin is disabled by means of `NODE_ENV` in the Docker build,
because for now the Docker image is only used in prod, and in prod we
have Zuplo handling CORS for us.
Run `yarn dev` and run the embed frontend with the API host set to
`http://localhost:3000`; make sure calculations succeed, and the CORS
requests are visible in web inspector and in the server log.
Build and run the Docker image; run the embed frontend against it and
make sure the CORS preflight requests fail.
> Add CORS plugin for Fastify, in non-production

- src/routes/v1.ts
- src/schemas/v1/incentive.ts
- test/fixtures/il-60304-state-utility-lowincome.json
- test/fixtures/v1-02807-state-items.json
- test/fixtures/v1-02903-state-utility-lowincome.json
- test/fixtures/v1-15289-homeowner-85000-joint-4.json
- test/fixtures/v1-80517-estes-park.json
- test/fixtures/v1-80517-xcel.json
- test/fixtures/v1-84106-homeowner-80000-joint-4.json
- test/fixtures/v1-az-85701-state-utility-lowincome.json
- test/fixtures/v1-az-85702-state-utility-lowincome.json
- test/fixtures/v1-co-81657-state-utility-lowincome.json
- test/fixtures/v1-ct-06002-state-utility-lowincome.json
- test/fixtures/v1-dc-20303-state-city-lowincome.json
- test/fixtures/v1-ga-30033-utility.json
- test/fixtures/v1-il-60202-city-lowincome.json
- test/fixtures/v1-mi-48103-state-utility-lowincome.json
- test/fixtures/v1-mi-48825-city-lowincome.json
- test/fixtures/v1-nv-89108-state-utility-lowincome.json
- test/fixtures/v1-ny-11557-state-utility-lowincome.json
- test/fixtures/v1-or-97001-state-lowincome.json
- test/fixtures/v1-pa-17555-state-lowincome.json
- test/fixtures/v1-va-22030-state-utility-lowincome.json
- test/fixtures/v1-vt-05401-state-utility-lowincome.json
- test/fixtures/v1-vt-05845-vec-ev-low-income.json
- test/fixtures/v1-wi-53703-state-utility-lowincome.json
This is the last piece to unlock updating the incentives to have
multiple items.
Embed frontend is already updated to not read this field.
Don't merge until rewiringamerica/consumer#1138 is deployed.
`yarn test`.
> Remove the singular item field from v1

- .eslintrc.cjs
- scripts/export-to-google-sheets.ts
- scripts/generate-spanish-descriptions.ts
- scripts/incentive-spreadsheet-to-json.ts
- scripts/lib/authority-and-program-updater.ts
- scripts/lib/format-converter.ts
- scripts/spreadsheets-health.test.ts
- src/lib/state-incentives-calculation.ts
- src/lib/states.ts
I'm personally opposed to `if (condition) doStuff()`; I think it's
best to always have braces in those situations to avoid silly and
potentially quite consequential mistake. This adds an eslint rule to
enforce that, and fixes all existing instances.
`yarn lint`, `yarn test`
> Add lint rule to enforce braces on control flow statements

- package.json
- yarn.lock
We run 18.18.0 in prod (as determined at the top of the Dockerfile), so upgrade the types package to match.
`yarn tsc` passes.
> Upgrade @types/node to match our prod node version

- scripts/incentive-spreadsheet-registry.ts
- scripts/spreadsheets-health.test.ts
I would love it if we didn't add any more spreadsheets to the
registry, but in case we do, I want them to be used with the script,
and passing the health check, from the start, so make it the default
to run the health check.
`yarn check-spreadsheet-health` has the same result as before. (There
are a few states failing because of new translations.)
> Run spreadsheet health check by default

- data/RI/incentive_relationships.json
- data/RI/incentives.json
- src/data/state_incentive_relationships.ts
- test/data/schemas.test.ts
While scanning the RI data for an unrelated reason
(https://app.asana.com/0/1206661332626418/1205768907565555), I noticed
that `prerequisites` was misspelled in the relationships file. This
led me to discover a whole cascading series of issues:
- The schema for relationships files did not include
`additionalProperties: false` which would have caught this. I added
that.
- The schemas test wasn't even testing the RI relationships file
because it relied on a redundant and outdated list of relationships
files. I deleted the redundant list and made it use the real one.
- The prereqs contained a reference to an incentive that wasn't in the
data: it was a smart thermostat incentive that had been marked as
"omit" in the spreadsheet (from before we had smart thermostats
represented). Un-omitted …
> Fix some issues with RI data

- data/low_income_thresholds.json
- scripts/incentive-spreadsheet-to-json.ts
- scripts/spreadsheets-health.test.ts
- scripts/update-fixtures.sh
- src/data/low_income_thresholds.ts
- src/lib/low-income.ts
- src/lib/state-incentives-calculation.ts
- test/data/low_income_thresholds.test.ts
- test/data/schemas.test.ts
- test/fixtures/v1-vt-addison-co-low-income.json
- test/fixtures/v1-vt-bennington-co-not-low-income.json
- test/routes/v1.test.ts
- test/scripts/data-refiner.test.ts
- test/scripts/incentive-spreadsheet-to-json.test.ts
This has been hanging over our heads since Vermont, but now NY's HEAR
program has them, so it's time to actually do it.
I added a `type` field to each threshold definition, which can have
the values `hhsize` or `county-hhsize`, indicating the sequence of
keys to be used with the `thresholds` structure. Counties are
identified by FIPS code, same as in the authorities files.
To demonstrate this working, I updated the county-specific Vermont
incentives (it's a lot less data than the NY ones, which I'll do
separately).
I've also switched the low-income-thresholds JSON-Schema-to-TS logic
away from ajv and to `json-schema-to-ts`. The latter is what I prefer
to use for this because it's what Fastify uses to turn endpoint
schemas into types, and I think it's worthwhile to have everything use
the …
> Support per-county low income thresholds

- src/data/types/items.ts
Removing these from the enum was over-eager, because the embed and PEP
clients are sending them as part of the `items` request param.
Adding them back lets us deploy the split-items change without
breaking the clients. Once the clients are updated, these enum values
can be removed again.
Run unmodified embed frontend against local backend without this
change; see the error on any form submission. Apply this change to the
backend; make sure the calculator successfully shows results.
> Add heat_pump_air_conditioner_heater and weatherization back to items enum

- data/CO/incentives.json
While working on this [ticket](https://app.asana.com/0/1207304265252553/1207304265868269/f) to set up the initial seed for the incentive_admin I ran into an error with CO incentive ID duplicates. This change updates those IDs in the source to avoid the unique constraint downstream.
> Update duplicate CO IDs

- data/AZ/incentives.json
- data/CT/incentives.json
- data/NY/incentives.json
- data/RI/incentives.json
- data/VA/incentives.json
- data/VT/incentives.json
- data/low_income_thresholds.json
To aid in ingesting the low income thresholds data in incentive admin with this [ticket](https://app.asana.com/0/1207304265252553/1207304265868262/f), I've updated the low_income reference keys to be unique. This uniqueness constraint will exist in the relational database in incentive admin.
> Update low income keys to be unique

- src/data/state_incentive_relationships.ts
- test/snapshots/v1-dc-20303-state-city-lowincome.json
- test/snapshots/v1-mi-48825-city-lowincome.json
It's way too easy to forget to add this when adding a new state. Do
what's done for authorities.json files and just read them all by
iterating over state codes.
The MI and DC relationships files actually weren't being read in, so
this does cause visible changes (two incentives that should have been
excluded, weren't).
`yarn test`
> Don't list out relationships files explicitly

- src/schemas/v1/incentive.ts
- test/snapshots/il-60304-state-utility-lowincome.json
- test/snapshots/v1-02807-state-items.json
- test/snapshots/v1-02903-state-utility-lowincome.json
- test/snapshots/v1-15289-homeowner-85000-joint-4.json
- test/snapshots/v1-80517-estes-park.json
- test/snapshots/v1-80517-xcel.json
- test/snapshots/v1-84106-homeowner-80000-joint-4.json
- test/snapshots/v1-az-85701-state-utility-lowincome.json
- test/snapshots/v1-az-85702-state-utility-lowincome.json
- test/snapshots/v1-co-81657-state-utility-lowincome.json
- test/snapshots/v1-ct-06002-state-utility-lowincome.json
- test/snapshots/v1-dc-20303-state-city-lowincome.json
- test/snapshots/v1-ga-30033-utility.json
- test/snapshots/v1-il-60202-city-lowincome.json
- test/snapshots/v1-mi-48103-state-utility-lowincome.json
- test/snapshots/v1-mi-48825-city-lowincome.json
- test/snapshots/v1-nv-89108-state-utility-lowincome.json
- test/snapshots/v1-ny-11557-state-utility-lowincome.json
- test/snapshots/v1-or-97001-state-lowincome.json
- test/snapshots/v1-pa-17555-state-lowincome.json
- test/snapshots/v1-va-22030-state-utility-lowincome.json
- test/snapshots/v1-vt-05401-state-utility-lowincome.json
- test/snapshots/v1-vt-05845-vec-ev-low-income.json
- test/snapshots/v1-vt-addison-co-low-income.json
- test/snapshots/v1-vt-bennington-co-not-low-income.json
- test/snapshots/v1-wi-53703-state-utility-lowincome.json
I've made sure that embed and PEP clients can both handle this field
being absent, and will assume incentives with the field absent are
eligible.
yarn test. Run the embed frontend against the local server and make
sure the results are unchanged.
> Remove "eligible" field from v1

- src/data/authorities.ts
- src/lib/incentives-calculation.ts
- src/lib/utilities-for-location.ts
- src/plugins/swagger.ts
- src/routes/v0.ts
- src/schemas/v1/calculator-endpoint.ts
- src/schemas/v1/image.ts
- src/schemas/v1/incentive.ts
- src/schemas/v1/location.ts
- src/schemas/v1/states-endpoint.ts
- src/schemas/v1/utilities-endpoint.ts
Added description strings for almost all the request and response
fields of all endpoints.
I didn't describe all the possible `items` enum values. That's going
to be very long, and I think is best left for its own separate
page. I'll add a link to that page from the doc string, once it's
ready.
There are some other OpenAPI hygiene changes like adding summaries for
endpoints (which makes them show up better in doc generators), and
adding operation IDs.
I snuck in two substantive changes:
- The same schema that represents authorities in the backend JSON data
was being used to represent them in the API. However, the JSON has
more fields than we want to expose in the API, so create a new
schema for authorities that excludes them.
- Remove the `include_beta_states` parameter from the utilities …
> Document all the fields

- src/data/types/amount.ts
It's "cubic feet per minute at 50 pascals". No incentives were using
this, and the embed frontend and PEp aren't either, so we can just go
ahead and do this.
`yarn test`
> Fix cmf50 -> cfm50

- src/schemas/v1/incentive.ts
I'm working on a script that code-generates a Markdown file of
response formats, for Zuplo docs. One challenge is dealing with deeply
nested object structures. I've got it rendering the docs for object
structures as a table if possible, but it's only possible if none of
the object's fields have descriptions with newlines. (You can't have
multiline values in table cells in Markdown, or at least not the
subset of Markdown that Zuplo supports.)
So, to allow rendering the `amount` structure as a table, I'm moving
the multiline part of the docs up to the top level of the structure,
rather than being on the `type` field.
Generate the spec from this, use my in-progress script to render it
into Markdown. Make sure the table rendered for `amount` looks correct.
> Move the detailed amount field docs up a level

- src/lib/state-incentives-calculation.ts
- src/schemas/v1/incentive.ts
- test/snapshots/il-60304-state-utility-lowincome.json
- test/snapshots/v1-02807-state-items.json
- test/snapshots/v1-02903-state-utility-lowincome.json
- test/snapshots/v1-15289-homeowner-85000-joint-4.json
- test/snapshots/v1-80517-estes-park.json
- test/snapshots/v1-80517-xcel.json
- test/snapshots/v1-84106-homeowner-80000-joint-4.json
- test/snapshots/v1-az-85701-state-utility-lowincome.json
- test/snapshots/v1-az-85702-state-utility-lowincome.json
- test/snapshots/v1-co-81657-state-utility-lowincome.json
- test/snapshots/v1-ct-06002-state-utility-lowincome.json
- test/snapshots/v1-dc-20303-state-city-lowincome.json
- test/snapshots/v1-ga-30033-utility.json
- test/snapshots/v1-il-60202-city-lowincome.json
- test/snapshots/v1-mi-48103-state-utility-lowincome.json
- test/snapshots/v1-mi-48825-city-lowincome.json
- test/snapshots/v1-nv-89108-state-utility-lowincome.json
- test/snapshots/v1-ny-11557-state-utility-lowincome.json
- test/snapshots/v1-or-97001-state-lowincome.json
- test/snapshots/v1-pa-17555-state-lowincome.json
- test/snapshots/v1-va-22030-state-utility-lowincome.json
- test/snapshots/v1-vt-05401-state-utility-lowincome.json
- test/snapshots/v1-vt-05845-vec-ev-low-income.json
- test/snapshots/v1-vt-addison-co-low-income.json
- test/snapshots/v1-vt-bennington-co-not-low-income.json
- test/snapshots/v1-wi-53703-state-utility-lowincome.json
Following up on #500 to remove the fields from the API definition.
(That previous PR was to remove them from the JSON data.) The embed
and PEP already ignore these fields in API responses.
`yarn test`
> Remove AGI, filing_status, ami_qualification from v1 API

- src/data/authorities.ts
- src/data/data_partners.ts
- src/data/geo_groups.ts
- src/data/state_incentive_relationships.ts
- src/data/types/states.ts
- src/lib/states.ts
- src/schemas/v1/states-endpoint.ts
- test/routes/v1.test.ts
At this point we should be treating states, DC, and territories as
equivalent by default. There are a couple of exceptions:
- The territories are listed separately because the tax calculation
needs to special-case them as zero federal income tax.
- States plus DC are listed separately because two data files
(ira_state_savings and solar_prices) only have entries for states
and DC. The former is only relevant for v0, and the latter is only
used to estimate solar system cost (and the result is not surfaced
anywhere in our current frontends), so it doesn't seem worth the
effort to try to fill in the equivalent data for the territories.
Those are the only uses of `STATES_PLUS_DC` remaining.
While I'm at it, change the `/v1/states` endpoint spec to not list out
all the states explicitly. …
> Change most instances of STATES_PLUS_DC to STATES_AND_TERRITORIES; clean up states endpoint spec

- data/CO/incentives.json
- data/geo_groups.json
For background, Tri-State G&T is a cooperative made of a bunch of
rural/municipal electric utilities. They're an electricity wholesaler;
individual customers do not deal with them.
While collecting data for multiple Tri-State members, we noticed that
their rebate info was just the same Tri-State branded PDF. So we coded
those incentives as belonging to Tri-State, and created a geo group
for it.
However, the presentation of this was confusing. There's no Tri-State
hosted place for this program info (the PDF is hosted on each member's
site), so the URL had to go to United Power, which is a utility.
So instead, just remove the Tri-State versions of the incentives. Each
member utility that uses the generic Tri-State PDF already has a copy
of those incentives, so the Tri-State ones are …
> Remove Tri-State G&T incentives; fix some CO EV incentives

- Dockerfile
- package.json
- yarn.lock
I don't quite understand everything that's going on here, but this
will get main deployable again.
Summary: the production Docker image build does not put a prebuilt
binary for the `sqlite3` package into the image, ever since I added
`sqlite3@^5.1.5` as an explicit dependency in #488.  I don't know why.
The package was already being installed (as a dependency of
`fastify-sqlite`) but adding the explicit dependency somehow changed
how it gets installed.
Upping the dependency to 5.1.7 fixes the problem. It causes 5.1.5 to
be installed within `node_modules/fastify-sqlite/node_modules` in the
prod image, with the prebuilt binary present. (5.1.7 is not installed
in the prod image at all, as I'd expect, since it's under
`devDependencies`.)
I'm also adding `--frozen-lockfile` to the yarn …
> Fix production build

- src/lib/incentives-calculation.ts
- test/snapshots/v1-02807-state-items.json
Reported in #525
The assumption that `items` is a singleton for IRA incentives was
broken a while ago. This meant that some IRA incentives were
incorrectly getting filtered out, because only `items[0]` was being
checked for overlap with `request.items`, rather than all of them.
The first-party calculator wasn't affected by this, because it passes
all the items in every query.
`yarn test`. This case was being exercised by an existing snapshot
test. The bug was introduced in 77d0ff6c7 and I dutifully updated the
snapshot there, but didn't notice the problem.
> Fix bug with filtering items in IRA incentives

- data/RI/incentive_relationships.json
- test/snapshots/v1-02807-state-items.json
- test/snapshots/v1-02903-state-utility-lowincome.json
This is a longstanding ticket that we somehow just never got around
to: having the income-qualified Clean Heat RI incentives exclude the
non-qualified ones.
34 (income-qualified ASHP + electrical upgrade) excludes 30
(non-qualified ASHP) and 32 (non-qualified electrical upgrade).
35 (income-qualified HPWH) excludes 33 (non-qualified HPWH).
RI-31 is a GSHP incentive which has no income-qualified equivalent, so
it's not excluded here.
https://app.asana.com/0/1206661332626418/1206661619324817
`yarn test`. Snapshot tests cover this case. Query the API with a RI
zip code and low income; make sure the non-income-qualified versions
aren't returned.
> Add relationships to Clean Heat RI

- data/VT/incentives.json
I think it should never have been in there? The rebate has always been
for both ducted and ductless AFAIK.
yarn test
> Remove "ducted" from GMP heat pump rebate

- src/app.ts
- src/schemas/v1/calculator-endpoint.ts
We've seen some confusion from API clients about how to pass multiple
values to this param, so clarify it in the param docs, and add the
ability to pass comma-separated values.
Removing `allowDots` from the qs config is OK because there are no
nested objects in query parameters anymore (since we flattened v1's
`location` parameter).
Will follow up by syncing the spec into Zuplo to publish the docs.
Curl `http://localhost:3000/api/v1/calculator` with the usual required
params, plus each of these:
- `?items=new_electric_vehicle&items=used_electric_vehicle`
- `?items[]=new_electric_vehicle&items[]=used_electric_vehicle`
- `?items=new_electric_vehicle,used_electric_vehicle`
Look in the server logs to make sure they were all parsed correctly
into a two-item array of items.
(Also it turns out …
> Clarify how to pass "items"; allow comma-separated values

- data/low_income_thresholds.json
- src/data/low_income_thresholds.ts
- src/lib/incentives-calculation.ts
- src/lib/low-income.ts
- src/lib/state-incentives-calculation.ts
- test/lib/incentive-relationships.test.ts
- test/lib/incentives-calculation.test.ts
- test/routes/v1.test.ts
- test/snapshots/v1-wi-53910-lowincome.json
- test/snapshots/v1-wi-53910-not-lowincome.json
Focus on Energy's income-qualified incentives are now based on AMI,
rather than per-state thresholds like last year. Fortunately, we
already have up-to-date AMI data at hand, so just plumb it in to the
low-income calculation.
I confirmed that the numbers on their site match the numbers in our
AMI database in a few randomly selected counties.
`yarn test` with new snapshot test (which fails on the old income thresholds).
> New low-income threshold type for AMI percentage; use in WI

- .gitignore
- data/CO/incentives.json
The titles on the embed for the Denver healthy homes incentives was set to "$0 off an electric/induction stove". I updated the sheet to a 100% discount to instead show "100% of cost of an electric/induction stove".
* `yarn test`
* Tested changes with local embed instance
> Fix Denver healthy homes titles

- data/AZ/incentives.json
- test/snapshots/v1-az-85701-state-utility-lowincome.json
- test/snapshots/v1-az-85702-state-utility-lowincome.json
"We just confirmed internally and unfortunately ADOR's solar panel credit was not renewed, so it would have to be removed from the result." -AZ Office of Resiliency
> Remove expired State of Arizona rooftop solar incentive

- data/ME/incentives.json
- test/snapshots/v1-me-04772-state-lowincome.json
From EM: "One other inconsistency is on the heat pump offers. We do not have a rebate for $2,000 for a ducted system. I think what is trying to be expressed there is that we have a Manufactured (Mobile) Home Initiative that pays the complete installation of a heat pump and removal of the fossil system with a customer co-pay of $2,000, where Efficiency Maine pays the remaining cost ($12,900)"
> update Efficiency Maine mobile home heat pump incentive

- src/plugins/swagger.ts
The previous link now goes to the wrong place with the main site
relaunch (the API marketing page instead of the Auth0 dev portal/login).
> Change link to dev portal login/signup

- data/MI/authorities.json
- data/MI/incentives.json
- data/MI/programs.json
- data/VT/incentive_relationships.json
- data/VT/incentives.json
- data/VT/programs.json
- data/low_income_thresholds.json
- src/data/low_income_thresholds.ts
- test/data/schemas.test.ts
- test/snapshots/v1-80517-xcel.json
- test/snapshots/v1-vt-05401-state-utility-lowincome.json
HERO and this codebase are currently out of sync -- both sides have
changes that the other side does not have. This is the first step to
resolving that situation.
I did a full export from HERO, and created this PR from only the parts
that were _added_; these are the updates that were in HERO but not in
JSON/spreadsheets.
With this done, we can once again do non-destructive imports from JSON
to HERO, to bring them fully back in sync and complete the deprecation
of spreadsheets.
There are two minor changes to the validation tests:
- Bumped the English character limit for descriptions up to 250, to
accommodate a long description for a VT incentive that we were asked
to put in. We do have a path to reducing this again, though; I've
made a ticket for it.
- Removed `minItems: 1` from the JSON …
> Export additive changes from HERO

- src/data/types/items.ts
- test/fixtures/test-incentives.json
I should have done this a while ago (adding them back in #486 was
supposed to be temporary) and this would have caught the problem that
caused rewiringamerica/incentive_admin#110.
`yarn test`. Search for both strings and find only the references in
the v0 code and data.
> Remove deprecated items from the enum

- data/geo_groups.json
- src/data/geo_groups.ts
- src/lib/state-incentives-calculation.ts
- test/data/geo_groups.test.ts
- test/lib/incentives-calculation.test.ts
Mass Save is the first example of this type, containing both utilities
and gas_utilities.
The code said that the request has to match on _all_ of the group's
defined categories, but I don't remember why I wrote it that way, and
it doesn't really make sense to me now.
In any case, this isn't an observable behavior change because there
were no multi-type groups before.
`yarn test`
> Add gas_utilities to geo groups; change multi-type matching logic

- src/data/state_incentives.ts
- test/data/schemas.test.ts
- https://app.asana.com/0/1208668890181682/1208930378081802
This hasn't made sense since we stopped having programs defined in
Typescript. Just iterate over the states like we do for other types of
state-specific data file.
This will avoid an easily-forgotten piece of busywork that happens
with every new state we add.
`yarn test`. Manually make a non-conformant change to a state
incentives JSON file and make sure the test fails.
> Stop manually loading in each state's incentives

- src/data/geo_groups.ts
- test/data/geo_groups.test.ts
- test/data/low_income_thresholds.test.ts
- test/data/utilities.test.ts
- test/lib/incentives-calculation.test.ts
- Let geo groups have an empty incentive list. This is not a reason to
block import; it's expected to happen sometimes.
- Let any incentive have a geo group, not just ones from `other`-type
authorities. The calculation code is already implemented this way:
the geo group becomes an additional filter on the incentive's
eligibility. So for e.g. an incentive from a `county` authority that
also has a geo group, you must be in that county _and_ match the geo
group.
- Improve error messages of one test
- Make Mass Save test independent of the actual number of incentives
- Skip the test that checks whether all `utility`-type authorities
exist in the zip-to-utility mapping. I do think we'll want it back
eventually, but unblocking import is more important for now.
With this state, tests pass after …
> Loosen some constraints to accommodate HERO import

- src/data/authorities.ts
- src/lib/incentives-calculation.ts
- src/schemas/v1/calculator-endpoint.ts
- test/routes/v1.test.ts
While implementing the Mass Save logic I realized that there's a
crucial distinction between a user _not having gas service_, and a
user _not specifying who their gas utility is_. (The former case
allows us to show more non-Mass Save utility incentives.)
My solution is to allow passing a special value of `none` to the
`gas_utility` param, meaning you affirmatively do not have gas
service. I'm anticipating that the calculator UI will offer options
like:
- National Grid
- Eversource
- Other
- I don't have gas service
"I don't have gas service" will result in the calculator sending the
special `none` value of the `gas_utility` param, while "Other" will
result in the param being absent.
This also adds logic to validate the parameter.
`yarn test` with new tests.
Test coverage of this isn't …
> Add "none" option to gas_utility param; validate param

- src/data/types/states.ts
- src/lib/incentives-calculation.ts
- test/lib/incentives-calculation.test.ts
Had to update some tests that assumed CT was in beta; in doing so I
found a bug that had been around for a while. We would have been
underestimating eligibility for clients that passed
`authority_types=other`; offhand I would guess that this is zero
clients. (It was not affecting the calculator, because the calculator
doesn't pass the `authority_types` param.)
`yarn test`
> Launch CT and OR; put IN and NM in beta

- src/lib/utilities-for-location.ts
- src/routes/v1.ts
- src/schemas/v1/utilities-endpoint.ts
- test/routes/v1.test.ts
This will make the API more suitable for general use, while still
supporting the calculator's intended behavior of only showing the gas
utility selector when necessary.
In addition to the recently added `gas_utilities` key in the
`/v1/utilities` response, I added `gas_utility_affects_incentives`.
If we don't have gas utility data for a state at all, both keys are
absent. If we have gas utility data, `gas_utilities` is always
populated and `gas_utility_affects_incentives` is present.
This way, clients who are just interested in which utilities serve the
area get whatever data we have. But the calculator can look at the
boolean flag to see whether it should show the selector.
Testing is incomplete because we only have gas utility incentives in
MA, which is special-cased in the code anyway. …
> Slightly rework gas utilities API

- package.json
- src/lib/dates.ts
- src/lib/state-incentives-calculation.ts
- test/lib/dates.test.ts
- test/snapshots/v1-15289-homeowner-85000-joint-4.json
- test/snapshots/v1-az-85701-state-utility-lowincome.json
- test/snapshots/v1-dc-20303-state-city-lowincome.json
- test/snapshots/v1-mi-48103-state-utility-lowincome.json
- test/snapshots/v1-pa-17555-state-lowincome.json
- test/snapshots/v1-wi-53703-state-utility-lowincome.json
- test/snapshots/v1-wi-53910-lowincome.json
- test/snapshots/v1-wi-53910-not-lowincome.json
- yarn.lock
Because of the more-than-just-a-day date formats we support, this is a
little bit subtle.
Note that this does not filter on incentive status, which we are not
exporting from HERO yet.
Note also that this uses js-joda, a competent date/time library;
Javascript's native Date is a nightmare.
Unit test of the new date logic. Snapshot tests reveal a bunch of
expired incentives that don't get returned anymore!
Related, though: this makes the results of snapshot test runs
**time-dependent**, which is really not ideal. This will cause
test failures on completely unrelated PRs. The proper solution is to
inject the "current time" as a parameter to the filtering logic, instead
of calling `LocalDate.now()`, but that may have to wait; we want to
get this change out before the end of year break.
> Filter out incentives with end dates in the past

- src/lib/utilities-for-location.ts
- test/routes/v1.test.ts
- [Asana](https://app.asana.com/0/1208668890181682/1209236041655647)
The ENERGY STAR electric utility dataset has a bunch of mappings to
zips that aren't ZCTAs. They aren't always consistent with the "parent
ZCTA" in our dataset. For example, in the case I added as a unit test:
- 01472 is not a ZCTA. Our dataset has 01450 as its parent ZCTA.
- `ma-groton-electric-light-dept` has a mapping to 01472, but _not_ to 01450.
It is clearly the case that Groton Electric Light covers the 01450
ZCTA (it encompasses the entire town of Groton), so arguably this is a
data error. Rather than go into a rabbit hole of trying to work out
the scope of the problem and update the zip/utility mappings to fix
it, I did this quick workaround to improve our results in these cases.
This change cannot decrease the …
> Check child zips for utility mappings as well

- data/tax_brackets.json
- test/lib/incentives-calculation.test.ts
- test/lib/tax-brackets.test.ts
- test/routes/v0.test.ts
Taken from here: https://www.irs.gov/pub/irs-drop/rp-24-40.pdf
These are the brackets that will apply to stuff you do this year, for
the tax return that you'll file in calendar year 2026.
We did skip the entire 2024 tax year, but fortunately, the bracket
numbers have no effect on the v1 API output. (Which raises the
question: is there any point in keeping this stuff once we delete v0?)
Updated tests. I did a couple of the calculations manually to confirm;
trusting the rest are correct since I didn't touch the calculation
logic.
> Update tax data to 2025 tax year

- .husky/post-checkout
- .husky/pre-commit
- package.json
- scripts/build.sh
- yarn.lock
- [Asana](https://app.asana.com/0/1208923746898025/1206215453677154)
This brings this repo in line with our other ones, particularly
`consumer` and the embed repo. It does the same `prettier --write` on
commit that the other repos do, but notably, this one exclude the
`data` directory, because running Prettier on that takes a _long_ time
thanks to the tens of thousands of lines of JSON. Those files are not
hand-edited and are formatted as they're written, so we're not missing
out by skipping them here.
It's easy to forget to rebuild the SQLite database after its inputs
change, and that can result in strange-looking test failures. So add a
post-checkout hook that looks for changes to its inputs and rebuilds
it if there are any. (It takes about 1 second; it's not a major
burden.)
On top of …
> Add husky and lint-staged; rebuild sqlite DB after checkout

- src/lib/state-incentives-calculation.ts
- test/lib/incentive-relationships.test.ts
- test/lib/incentives-calculation.test.ts
- test/snapshots/v0-80212-homeowner-80000-joint-4.json
- test/snapshots/v1-02903-state-utility-moderateincome.json
- test/snapshots/v1-15289-homeowner-85000-joint-4.json
- test/snapshots/v1-80517-estes-park.json
- test/snapshots/v1-80517-xcel.json
- test/snapshots/v1-co-81657-state-utility-lowincome.json
- test/snapshots/v1-dc-20303-state-city-lowincome.json
- test/snapshots/v1-ny-11557-state-utility-lowincome.json
- test/snapshots/v1-wi-53703-state-utility-lowincome.json
This change does two things:
- Don't return ineligible incentives from
`calculateStateIncentivesAndSavings`. Previously, they were being
returned, and then filtered out in the top-level route handler in
`v1.ts`. They were never returned in the API. This makes the
below change simpler.
- Draw a distinction between "real-life eligibility" params, and
"API-only" params. The latter are the `authority_types` and `items`
filters. They don't correspond to real-life incentive eligibility
criteria; they're just there for API clients.
The important thing here is that now the order of operations in
eligibility calculation is slightly different:
1. All of a state's incentives are partitioned into "eligible" and
"ineligible" based on real-life params: location, utility, owner
status, …
> Change order of filtering in state incentive calculation

- data/ira_incentives.json
- test/snapshots/v0-80212-homeowner-80000-joint-4.json
- test/snapshots/v1-02807-state-items.json
- test/snapshots/v1-15289-homeowner-85000-joint-4.json
- test/snapshots/v1-84106-homeowner-80000-joint-4.json
- test/snapshots/v1-vt-05845-vec-ev-low-income.json
- [Asana](https://app.asana.com/0/1208668890181682/1209198275861173)
To reflect that the credit is now deliverable as an upfront discount
at the point of sale (by being transferred to the dealership, I
think?). I removed the `(up to $7,500)` parenthetical from the
language in the ticket, to stay under the char limit, and because the
amount is in the `amount` field (which will be prominently shown in
the calculator).
Re: the ask to link to the DOE's `fueleconomy.gov` site instead: I
decided not to, because the [IRS page we currently link
to](https://www.irs.gov/credits-deductions/credits-for-new-clean-vehicles-purchased-in-2023-or-after)
is not bad, and it links to fueleconomy.gov itself. (In contrast,
fueleconomy.gov does not link to any IRS page as far as I can see.)
Snapshot tests …
> Update language for federal EV tax credit

- src/lib/state-incentives-calculation.ts
- src/lib/tax-brackets.ts
- test/lib/tax-brackets.test.ts
- [Asana](https://app.asana.com/0/1208668890181682/1209428558323182)
We have state tax credits for these, so we ought to calculate their taxes.
I learned through doing this that a lot of MA tax calculators on the
internet (or at least the ones that have good SEO) are wrong; they
either don't account for the millionaire's tax or use the wrong
threshold for it.
I also learned that Wikipedia has the best SEO for "new mexico state
tax" but the table on the page is wrong; it doesn't include the top
marginal rate of 5.9%, which is new in 2021.
I'm left with a general feeling of irritation that I'm not quite sure
what to do with.
New unit tests. The NM expected values are the ones given in the
source document. The MA values were calculated by me actually going
through MA tax forms and following …
> Calculate taxes for MA and NM

- src/lib/incentives-calculation.ts
- src/lib/state-incentives-calculation.ts
- src/lib/tax-brackets.ts
- test/lib/incentives-calculation.test.ts
- test/lib/tax-brackets.test.ts
- [Asana](https://app.asana.com/0/1208668890181682/1209381661213139)
Do this separately for federal and state incentives.
This also fixes a bug in the MA state tax calculation I just added,
which resulted in negative tax liability for incomes below the
personal exemption.
New unit test.
> Filter out tax credits if we compute zero tax liability

- src/lib/incentives-calculation.ts
- src/lib/low-income.ts
- src/lib/state-incentives-calculation.ts
- src/schemas/v1/calculator-endpoint.ts
- test/lib/incentives-calculation.test.ts
- test/routes/v1.test.ts
- [Asana](https://app.asana.com/0/1208668890181682/1208959599500050)
If it's not passed, don't filter out tax credits (as we do if tax owed
is zero), and assume we don't meet filing-status-dependent low-income
thresholds.
Also don't cap the tax credit savings total at tax owed. This is a
non-issue in practice: the number is only shown in API v0, which
still requires filing status to be passed.
Unit tests
> Make filing status optional in v1

- src/lib/mass-save.ts
They explicitly allow double-dipping with Mass Save for dryer rebates,
and also (depending on your existing fuel) for stove, HPWH, and heat
pump rebates. We'll note the fuel restrictions in the descriptions of
their incentives.
`yarn test`
> Add Wellesley MLP to Mass Save exception list

- src/lib/incentives-calculation.ts
- test/lib/incentives-calculation.test.ts
MA residents are already eligible for free energy audits, so that incentive will be filtered from the caclulator results for that location. 
https://app.asana.com/0/1208668890181682/1209811787832381/f
- New unit test
- Validated calculator results do not include the incentive using Bruno
> Exclude federal energy audit for MA residents

- package.json
- src/@types/geocodio-library-node.d.ts
- src/lib/location.ts
- yarn.lock
Basically had to redo #700 after the geography overhaul, which
significantly changed the code that calls Geocodio.
`yarn tsc`
`yarn test`
> Upgrade to geocodio library with types

- .github/workflows/import.yml
- scripts/zcta-to-geography/.gitignore
- scripts/zcta-to-geography/README.md
- scripts/zcta-to-geography/requirements.txt
- scripts/zcta-to-geography/zcta-to-geography.py
- [Asana](https://app.asana.com/1/1200412452784804/project/1208668890181682/task/1210059285909602)
- In the import workflow, detect whether `geographies.csv` has
changed, and run zcta-to-geography.py if so. This entails adding
steps to set up Python and install dependencies.
- Update the script to download the required shapefiles directly from
the Census server. This is the simplest solution and I'm content to
just go with it until it proves to be a problem. I think the most
likely way it will become a problem is if the download becomes
unreliable; in that case, my first-resort fix would be to put the
files on Cloud Storage.
The files are cached locally, for when you're working on the script,
but this caching has no effect on Github Actions (because it starts
with a clean container every …
> Run zcta-to-geography.py from the "import from HERO" workflow

- src/data/types/capital-types.ts
- src/data/types/program.ts
- [Jira](https://rewiringamerica.atlassian.net/browse/RAT-366)
The new merge script that @SkittyWitty wrote (rewiringamerica/api-zuplo#140) trips up on schema names that have periods in them (because it uses lodash to follow period-delimited paths through a JSON object). Rather than try to deal with that in the script, I just fixed the schema names; there's no reason to have the `.schema.json` part.
`yarn test`. Fetch /spec.json locally and diff it with the spec generated from main to make sure removing the string `.schema.json` is the only difference.
> Remove periods in schema $id

- .github/workflows/import.yml
Forgot about this.
This time I tested locally with `act`.
I had to add the extra steps of `apt update; apt install sqlite3` to
make it work, because the image `act` uses doesn't have sqlite3
installed. The Github image does, though, as demonstrated by (a) the
fact that the `yarn build` command in the test.yml workflow Just
Works, and (b) Github's [own docs](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md#databases).
> Build the SQLite database before updating snapshots

- data/ira_incentives.json
- test/snapshots/v0-80212-homeowner-80000-joint-4.json
- test/snapshots/v1-02807-state-items.json
- test/snapshots/v1-15289-homeowner-85000-joint-4.json
- test/snapshots/v1-84106-homeowner-80000-joint-4.json
- test/snapshots/v1-vt-05845-vec-ev-low-income.json
- [Jira](https://rewiringamerica.atlassian.net/browse/RAT-686)
- 25C (energy efficient home improvement) and 25D (residential clean
energy) are available for installations that happen before the end
of 2025.
- 30D (new EV) and 25E (used EV) are available for vehicles purchased
before the end of September.
- 30C is available for installations before the end of June 2026.
Note that in the v0 API, the end date is just a number signifying the
year, so these are returned in v0 as just `2025` (or `2026` in one
case). v0 is about to be deleted, so I'm not worried about that.
As written, this means that we'll completely stop showing them after
the end date. However, people who want to claim them will still need
to remember to do so, come tax time next year; I'm not sure if we'll
want to keep …
> Update end dates of IRA tax credits

- data/ira_incentives.json
- test/snapshots/v0-80212-homeowner-80000-joint-4.json
- test/snapshots/v1-02807-state-items.json
- test/snapshots/v1-15289-homeowner-85000-joint-4.json
- test/snapshots/v1-84106-homeowner-80000-joint-4.json
They aren't going to reset yearly anymore :(
Also fixed some missing Spanish copy for the energy audit credit.
`yarn test`. `git-grep -i 'yearly reset'` has no results.
> Remove "yearly reset" from IRA credit copy

- src/lib/incentives-calculation.ts
- src/lib/state-incentives-calculation.ts
- test/lib/incentive-relationships.test.ts
- test/lib/incentives-calculation.test.ts
- test/routes/v1.test.ts
- test/snapshots/v1-sd-no-coverage.json
This was caused by the big post-v0 overhaul I just did.
`calculateStateIncentive` was computing the `coverage` part of the API
response by whether the list of incentives passed to it was empty. In
the overhaul, I made it so that it's _never_ empty (it always includes
IRA incentives), so the returned `coverage` was always non-null.
This changes it to compute `coverage` one level up, which allows for
some code simplification.
New snapshot test that failed before the change. Existing tests pass.
> Fix bug in coverage reporting

- package.json
- scripts/ny-empower-income-limits.ts
- src/@types/sqlite.d.ts
- src/lib/ami-evcredit-calculation.ts
- src/lib/location.ts
- src/lib/utilities-for-location.ts
- src/plugins/sqlite.ts
- src/routes/v1.ts
- test/data/geo_groups.test.ts
- test/data/geographies.test.ts
- test/data/utilities.test.ts
- test/lib/ami-evcredit-calculation.test.ts
- test/lib/incentives-calculation.test.ts
- yarn.lock
The combination of sqlite libraries we've been using hasn't been
updated for a while. In particular, it seems `sqlite3` doesn't have a
prebuilt binary for Node 22, which breaks the Docker build: it needs
Python within the builder image to compile SQLite, and it's not there,
and it's a whole mess.
This PR switches everything to use `better-sqlite3` instead: it's
actively maintained, and claims various advantages, which you can read
about [in their readme](https://github.com/WiseLibs/better-sqlite3).
You'll notice that the new lib is synchronous. The rationale for this
is explained in the better-sqlite3 docs, but as additional reassurance
for this context, our queries are so fast anyway and our traffic is so
low that there's not going to be any noticeable difference.
`yarn test`
`yarn dev` …
> Convert to better-sqlite3
