rewiringamerica/api.rewiringamerica.org

scripts/README.md

Document how to fill out an entry in the incentive spreadsheet registry. Add more links.

Document how to fill out an entry in the incentive spreadsheet registry. Add more links.

---

data/NY/incentives.json
test/fixtures/v1-ny-11557-state-utility-lowincome.json

Quick fix based on feedback from the testing party. Also updated it in the spreadsheet.

Fixing grammar in NY incentive based on feedback.

---

data/VA/incentives.json
data/authorities.json
scripts/update-fixtures.sh
test/fixtures/v1-va-22030-state-utility-lowincome.json
test/routes/v1.test.ts

Fix utility provider name, caught in calculator testing party.

Fix VA Dominion Energy name throughout incentives

---

data/programs.json
test/fixtures/v1-vt-05401-state-utility-lowincome.json

Make Vermont program names more specific to item type per VEIC request.

Modify Vermont program names

---

scripts/incentive-spreadsheet-registry.ts
scripts/incentive-spreadsheet-to-json.ts
scripts/lib/spreadsheet-mappings.ts
test/data/spreadsheets-health.test.ts

This test validates that the spreadsheets match our collected data schema. It is skipped right now, but likely next step is to add a workflow that sets an environment variable so we can run it only in those contexts.
CO and AZ are the only tests currently passing :( but I will circle back to the others later.

Add spreadsheet health test and register CO and AZ as passing states.

---

scripts/incentive-spreadsheet-to-json.ts
scripts/lib/format-converter.ts
scripts/lib/spreadsheet-standardizer.ts
src/data/state_incentives.ts

This better captures that this is parallel with the StateIncentive type/schema.

Rename CollectedFields to CollectedIncentive.

---

scripts/lib/spreadsheet-standardizer.ts
test/scripts/incentive-spreadsheet-to-json.test.ts

Noticed this oversight and didn't want to erase any work made on the Spanish translations :)

Propagate Spanish translations in spreadsheet-to-json.

---

data/CO/incentives.json
data/authorities.json
data/programs.json
src/data/programs.ts
test/data/utilities.test.ts

In preparation of adding stricter tests that verify spreadsheet and JSON data are aligned, I'm updating the CO data. I thought about doing it in the same PR, but it seemed like it would muddy the diffs a bit.
This was the result of me changing the spreadsheet data and then rerunning the spreadsheet-to-json flow. Other states may have more varied changes, but here we just have:
- authority and program renames
- field reordering
I didn't see any actual content changes aside from these.

Update CO data to align with spreadsheet.

---

test/fixtures/v1-co-81657-state-utility-lowincome.json
test/routes/v1.test.ts

"My mental model of how those tests work must be wrong" -> nope, just executed poorly.

Correctly wire up CO v1 test.

---

data/AZ/programs.ts
data/CO/programs.ts
data/CT/programs.ts
data/DC/programs.ts
data/IL/programs.ts
data/MI/programs.ts
data/NV/programs.ts
data/NY/programs.ts
data/RI/programs.ts
data/VA/programs.ts
data/VT/programs.ts
src/data/ira_incentives.ts
src/data/programs.ts
src/data/state_incentives.ts
src/routes/v0.ts
src/routes/v1.ts
test/data/schemas.test.ts

Per [Slack conversation](https://rewiringameri-g3x1100.slack.com/archives/C04E4THEGMT/p1709583657513919), it'll be better to have a single data format for this program information.
This isn't strictly necessary and I am open to pushback, but I think it's better from an organizational and automation perspective to also split up these files by state, which I've done here. They are getting pretty large, and being able to simply create a new file or overwrite an existing one when updating programs is easier than needing to insert in the right place.

Consolidate programs.json into programs.ts.

---

data/IL/incentives.json
scripts/incentive-spreadsheet-registry.ts

I needed to make some minor spreadsheet changes, but overall these states were pretty easy. The diffs in IL are because Spanish translations were added.

Add easy states to sync test.

---

scripts/incentive-spreadsheet-to-json.ts
scripts/spreadsheets-health.test.ts
test/scripts/incentive-spreadsheet-to-json.test.ts

I'd love to pass this off as me being deliberate about small, incremental changes but I just forgot in the previous PR.

Actually link in geogroups functionality in spreadsheet-to-json.

---

data/ira_incentives.json
test/fixtures/v0-80212-homeowner-80000-joint-4.json
test/fixtures/v1-15289-homeowner-80000-joint-4.json
test/fixtures/v1-80212-homeowner-80000-joint-4.json

lowercase EV charger link

---

data/NV/incentives.json
data/PA/incentives.json

1. Add PA Spanish translations
2. Update 2 NV incentives w/ Spanish translation updates (I updated the English description with testing party feedback after NV Spanish language translations were complete, so Gaby went back and updated these 2)
PA spreadsheet: https://docs.google.com/spreadsheets/d/1H4hVUAwmEshbndeY2lFdnyk53qPZhoR5o1du5G1DVMw/edit#gid=616584455
NV spreadsheet: https://docs.google.com/spreadsheets/d/1w6c4lAlNGTKEuN_X00mAcK3Xs6NGM1aT5XFbhjd1CGo/edit#gid=995688950

PA Spanish translations

---

scripts/check-data-freshness.ts
scripts/lib/website-comparisons.ts

This better separates the status check test from the functions that will eventually be used for multiple checks for PDF and HTML content.

Move checkUrlDataAvailability to website-comparisons.ts

---

scripts/README.md

I'd recommend actually running through the process to make sure everything works as described, especially the authentication part, before approving.

Add documentation for json-to-spreadsheet process.

---

data/GA/incentives.json
test/fixtures/v1-ga-30033-utility.json

Addresses GA QA and adds Spanish translations.
QA fixes:
- splits out GA power heat pump incentives into 2 separate incentives, one for geothermal heat pumps and one for mini splits

GA QA fixes and Spanish translations

---

data/IL/incentives.json
scripts/update-fixtures.sh
src/data/programs/il_programs.ts
src/data/types/states.ts
test/fixtures/il-60304-state-utility-lowincome.json

This excludes the Corn Belt Energy GeoCents program, because we don't
yet have a way to represent its structure (a payout for installation,
followed by a per-month fee to use the system). Figuring out what to
do about that is tracked here:
https://app.asana.com/0/1206661332626418/1206629812396080
`yarn test`. Run update fixtures script, see no changes to
fixtures. Run `yarn check-spreadsheet-health` and see the IL
spreadsheet is fully synced.

Launch Illinois

---

data/PA/incentives.json
src/data/programs/pa_programs.ts

Couple of new rebates that PA DEP emailed about. See ticket for more details: https://app.asana.com/0/1206629812394927/1207049982896669/f
Additions:
1. UGI utilities heat pump and appliance rebates
2. PECO EV rebate

Add UGI rebates and PECO EV rebate

---

data/CO/incentives.json
data/geo_groups.json
src/data/programs/co_programs.ts
test/fixtures/v1-80517-estes-park.json
test/routes/v1.test.ts

[Asana Ticket](https://app.asana.com/0/1206661332626418/1207093680265524/f)
Update summary
- Data Refresh for Colorado Springs Utilities
- Adds missing incentives for co-san-miguel-power-association
- Adds missing incentives for Efficiency Works partner utilities. 
- Cleans up IL test flags.

CO Incentive Feedback 

---

data/CO/incentives.json
src/data/programs/co_programs.ts
test/fixtures/v1-80517-estes-park.json
test/fixtures/v1-80517-xcel.json
test/fixtures/v1-co-81657-state-utility-lowincome.json

Adds Colorado Energy Office Heat Pump Tax Credit Incentives
Resource: https://energyoffice.colorado.gov/hptc
Asana Ticket: https://app.asana.com/0/1206661332626418/1207142221464012/f

Adds Colorado Energy Office Heat Pump Tax Credit Incentives

---

data/CO/incentives.json
src/data/programs/co_programs.ts

Feedback received through Google Fellow

Change program URL for Denver battery storage program

---

data/VT/incentives.json

There are some new translations for newly added incentives, and I
removed the redundant words "dolares" from everything.
`yarn test`

New/updated Spanish for VT

---

data/IL/incentives.json

Add updated and missing Spanish translations
https://app.asana.com/0/1206661332626418/1207290360962448/f

Add updated and missing Spanish translations

---

data/MI/incentives.json

Add spanish translations for MI
https://app.asana.com/0/1206661332626418/1207290360962448/f

Add spanish translations for MI

---

data/DC/incentives.json

Add Spanish translations
https://app.asana.com/0/1206661332626418/1207290360962448/f

Add DC Spanish translations

---

data/PA/incentives.json

Add/Update Spanish translations.
https://app.asana.com/0/1206661332626418/1207290360962448/f

Add/Update Spanish translations PA

---

data/IL/incentives.json
data/MI/incentives.json
data/WI/incentives.json
test/data/schemas.test.ts
test/snapshots/v1-wi-53703-state-utility-lowincome.json

Issue reported here: https://rewiringameri-g3x1100.slack.com/archives/C04E4THEGMT/p1717445434575539
Incentive link: https://www.consumersenergy.com/residential/save-money-and-energy/rebates/heating-and-cooling

Update invalid max amount for MI-65

---

data/VT/incentives.json
src/data/programs/vt_programs.ts
test/snapshots/v1-vt-bennington-co-not-low-income.json

Update the incentives for VT.
Asana link: https://app.asana.com/0/1207456219977120/1203684030594289
Testing: `yarn test`

Update VT incentives

---

data/WI/incentives.json

Translation was done in the spreadsheet and synced here via script.

Add Spanish to WI incentives

---

.github/workflows/import.yml
scripts/incentive-admin-import.ts

Adds an import workflow to pull data from Incentive Admin. 
- [_Asana_](https://app.asana.com/0/1207304265252553/1207352903940800/f)
- [Example PR](https://github.com/rewiringamerica/api.rewiringamerica.org/pull/546)
- adds `.github/workflows/import.yml`
- adds `scripts/incentive-admin-import.ts` 
- run incentive admin in one terminal and in another run `npx ts-node scripts/incentive-admin-import.ts` to verify the import script. Changes will be added to your repository for comparison.
- check out the example pr https://github.com/rewiringamerica/api.rewiringamerica.org/pull/546
- Test triggering of the workflow manually https://docs.github.com/en/actions/using-workflows/manually-running-a-workflow. This should be enabled once these changes are on `main`. 
- Update `INCENTIVE_ADMIN_HOST` …

Adds an Import Workflow to pull data from Incentive Admin. 

---

scripts/README.md

Update README.md to document Incentive Admin Integration

Update README.md to document Incentive Admin Integration

---

data/CO/incentives.json
data/CO/programs.json
data/low_income_thresholds.json

[Asana Task](https://app.asana.com/0/1207249595308796/1207162679730151/f)
Updated incentives data sheet with additional incentives for Denver Healthy Homes program and ran the spreadsheet to json script with the new data.
* `yarn test`
* Used curl with test server to validate incentives appear for an eligible Denver address

Update data files for Denver Healthy Home's incentives

---

.github/workflows/import.yml

Update Incentive Admin import workflow to hit admin api now that it is available

Update Incentive Admin import workflow to hit admin api now that it is available

---

package.json
yarn.lock

It was used to codegen the TS programs files, but that's all gone now.

Remove ts-morph

---

package.json
test/data/schemas.test.ts
yarn.lock

This required upgrading Tap (the test library) because of some
incompatibility (tapjs/tapjs issue 976) that I don't fully understand,
but whatever.
Tests pass.
Ran the server and made some manual requests successfully.

Upgrade TypeScript to latest version

---

data/RI/programs.json
test/snapshots/v1-02903-state-utility-lowincome.json
test/snapshots/v1-02903-state-utility-moderateincome.json

They've updated their website recently. (No need to change the program
IDs; those aren't shown to users.)
`yarn test`

Update RI Energy URLs

---

scripts/incentive-spreadsheet-to-json.ts
scripts/lib/format-converter.ts

- Sort incentives by id _numerically_, to match the way HERO has
exported them
- Uniquify array fields

Two tweaks to spreadsheet import to fix irrelevant differences

---

src/lib/mass-save.ts
src/lib/state-incentives-calculation.ts
test/lib/mass-save.test.ts

This is pretty extensively explained in comments, so I won't repeat myself here.
I believe the new unit test is fully comprehensive?

Implement the Mass Save eligibility rule

---

src/data/types/states.ts

Launch IN and NM

---

scripts/incentive-admin-import.ts

Remove try-catch blocks for HERO import script so the github work flow fails on any errors from the HERO endpoints
https://app.asana.com/0/1208032460888564/1209171425611388/f
Run HERO locally and modify export endpoints to always throw an error. Then validate that the API's import script exits with an error instead of catching them.

Make the API import workflow fail on error from a HERO export endpoint

---

src/lib/mass-save.ts
src/lib/state-incentives-calculation.ts
test/lib/mass-save.test.ts

We misunderstood the rule the first time. If you have MLP electric and
Mass Save gas, that doesn't mean you're ineligible for all the MLP
incentives. Rather, you can't claim the MLP's incentives for _items_
that Mass Save has incentives for.
This computation is actually a good bit simpler, and it slots into the
overall eligibility calculation more cleanly. It's actually just
programmatically implementing a bunch of exclusion relationships
("supersedes" in HERO) that would be very tedious to create and
maintain manually.
In particular, in that scenario, you could claim MLP incentives for
things like EVs and solar panels, because Mass Save doesn't cover
those. (Note the crucial distinction that some Mass Save _member
utilities_ have their own incentives for EVs and solar panels, outside
the …

Redo the Mass Save logic

---

src/data/types/states.ts

https://app.asana.com/0/1208668890181682/1209448079074203
Move some state with data added from our partners to beta status
`yarn test` and checked `/api/v1/states` response

Set some more states to Beta status

---

data/ira_incentives.json
test/snapshots/v0-80212-homeowner-80000-joint-4.json
test/snapshots/v1-02807-state-items.json
test/snapshots/v1-15289-homeowner-85000-joint-4.json
test/snapshots/v1-84106-homeowner-80000-joint-4.json

- [Asana 1](https://app.asana.com/0/1208668890181682/1209719050038571)
- [Asana 2](https://app.asana.com/0/1208668890181682/1209719050038567)
Update our estimated average value of the GSHP credit, and reflect
that all the 25C credits are available to renters.
yarn test

Minor updates to IRA credits

---

src/lib/location.ts

- [Asana](https://app.asana.com/1/1200412452784804/project/1208668890181682/task/1209940781479960?focus=true)
- [Github conversation](https://github.com/rewiringamerica/embed.rewiringamerica.org/pull/231#discussion_r2038071911)

add error handling for geocode error

---

data/MN/incentives.json
data/MN/programs.json
data/TX/incentives.json
data/WY/incentives.json
data/geo_groups.json

This PR updates the API data files, using data maintained by the [Incentive Admin](https://github.com/rewiringamerica/incentive_admin).

Incentive Admin Update

---

.github/workflows/import.yml

I can't think of a reason not to do this, and it takes care of the
last routine cause of automated PRs not being mergeable without human
intervention.
We'll see how this goes with the next update!

Have the import workflow update snapshots automatically

---

README.md

- [Jira](https://rewiringamerica.atlassian.net/browse/RAT-625)
The main thing is to remove public mentions of a roadmap (we've never
kept this up to date; no reason to think we'll get better about it
now) but I also did a sweep through the whole thing to fix other
obvious outdated text.
Read it

Stop talking about roadmap; other readme updates
